// data.js - Datos constantes y configuración

// Datos de ejemplo
const OPERATORS = [
    "4332: ACEVEDO ANAYA EDUARDO YAHIR",
    "2767: ACOSTA ACOSTA GABRIELA",
    "2525: AGUILAR MARTINEZ MARIA TERESA",
    "0034: AGUILAR PADILLA EUSEBIO",
    "0452: AGUILAR BALDERAS ALFREDO",
    "4481: AGUILAR GONZALEZ CINTHIA VERONICA",
    "4068: ALDAMA GARCIA GABRIEL ALFREDO",
    "1375: ALEMAN MOLINA JUAN CARLOS",
    "3555: ALFARO GOMEZ VICTOR HUGO",
    "4277: ALMARAZ BADILLO JUAN CARLOS",
    "4442: ALONSO VEGA EFRAIN",
    "3463: ALVARADO CARMONA PABLO",
    "4406: ALTAMIRANO TORRES GILBERTA",
    "4183: ALZATI GONZAGA LUIS GERARDO",
    "4102: ANDRADE JAUREGUI ROSARIO",
    "0042: ANGELES BECERRA DANIEL",
    "2864: ANGELES GARCIA JULIO",
    "3498: ANOTA LOPEZ ALEJANDRO",
    "0813: ARREDONDO CRUZ ELOY",
    "3980: ARREDONDO RODRIGUEZ JOSEPH JARET",
    "2834: ARREGUIN AGUILAR AMADOR",
    "3852: ARREGUIN MALAGON JUAN PABLO",
    "0886: ARREOLA FONSECA ALMA ISABEL",
    "2517: AYALA MORALES MARIA ROCIO",
    "4321: BAEZ RUIZ LIZETH JACQUELIN",
    "4326: BALBUENA CAMACHO LUIS ANGEL",
    "2554: BALDERAS ARAUJO ANA LAURA",
    "4482: BALDERAS ESTRADA DIEGO EDUARDO",
    "4314: BALDERAS RANGEL DANIEL",
    "4485: BALDERAS ROMERO BRISA GUADALUPE",
    "3744: BALDERAS ROMERO JOANA IVONE",
    "3709: BALTAZAR DEMETRIO CARLOS",
    "2700: BARRERA JAIME ANTONIO",
    "3721: BARRERA SANCHEZ SARAHI",
    "3868: BASALDUA MARTINEZ OLGA",
    "3389: BASALDUA MARTINEZ SILVIA",
    "2775: BAUTISTA CRUZ JULIO ANTONIO",
    "3348: BAUTISTA CRUZ NANCY MARISOL",
    "4464: BAUTISTA LEON EDUARDO",
    "4475: BAUTISTA SANCHEZ ANA GABRIELA",
    "1700: BECERRA RIVERA LUIS ALBERTO",
    "3111: BECERRIL CERVANTES LORENA",
    "0079: BERNAL TRUJILLO MARIA TERESA",
    "3776: BORJA GARCIA JORGE ARIEL",
    "0528: BORJA LEON LEANDRO DOLORES",
    "3450: BORJA URIBE JAQUELINA",
    "3930: BRACHO LAVARIEGA ROBERTO",
    "2475: BRIONES AVILA JOSE ARMANDO",
    "4276: CABRERA GARCIA EUGENIO",
    "2078: CABRERA GARCIA URIEL",
    "4223: CABRERA MORALES JOCELYN",
    "3645: CABELLO ROSALES ANGELES CRISTINA",
    "3587: CALLEJA SALAS ERIK",
    "1573: CAMACHO GOMEZ JOSE CRUZ",
    "4340: CAMACHO CORTES DOLORES ILEANA",
    "4393: CAMPOS PICHARDO ARMANDO",
    "3069: CANO QUEVEDO JUAN GABRIEL",
    "4240: CANTOR MORALES JERONIMO",
    "3558: CARDENAS BRIONES EMILIO",
    "0442: CARMONA CERDA PAOLA MAGALHY",
    "4269: CARRANZA GUARDADO AGUSTIN",
    "0634: CASTRO CASTILLO JULIO",
    "3153: CASTRO CASTILLO MA. DEL ROSARIO",
    "4113: CASTILLO SILVA VICTORIA",
    "3718: CENTENO BARRERA MAYRA ISABEL",
    "3725: CERVANTES CERVANTES ORLANDO",
    "4390: CERVANTES GARFIAS FABRICIO",
    "3446: CERVANTES MATEOS JOSE SALVADOR",
    "4289: CERVANTES ROSAS FRANCISCO JAVIER",
    "4249: CHAPA MELGAREJO JOHANNA",
    "3345: CHAVEZ GONZAGA JOSE ANTONIO",
    "4260: CHAVEZ RESENDIZ EMMANUEL",
    "0071: CHAVEZ VELAZQUEZ SILVESTRE",
    "0859: COBOS JOSE CARLOS",
    "4461: COLIN COLIN MAURICIO",
    "3848: CONZUELO MEDINA CARLOS OMAR",
    "3749: CORONA RESENDIZ MARIA BLANCA",
    "1100: CORONILLA ROMERO RAMON",
    "4353: CRUZ BOCANEGRA FEDERICO",
    "1256: CRUZ MATA JOSE JAIME",
    "3724: CRUZ RAMIREZ ROSA",
    "2333: DE LEON LOYOLA J GUADALUPE",
    "3950: DELOYA GARCIA ANTONIO",
    "3629: DIONICIO GONZALEZ GUADALUPE",
    "0115: DOMINGUEZ ABOYTES REYES",
    "3273: DOMINGUEZ MARTINEZ RAFAEL",
    "2226: ESCOTO GOMEZ VICTOR GABRIEL",
    "0109: ESCOTO GARCIA ANTONIO",
    "0056: ESCOTO GARCIA JUAN MANUEL",
    "0239: ESPINOZA ESCOBEDO MIGUEL ANGEL",
    "3716: ESPINOZA CABAÑAS JHON CARLO",
    "3570: ESPINOZA VEGA DIANA",
    "1089: ESTRADA SILVA ARTURO",
    "3767: FABIAN BARCENAS ALBERTO DANIEL",
    "3374: FIGUERA ZUÑIGA GABRIEL JESUS",
    "4096: FIGUEROA HERNANDEZ OSCAR",
    "4420: FLORES CERVANTES JOSE MARIA",
    "3243: FLORES MAYORGA OSCAR ANTONIO",
    "0890: FLORES RAMIREZ FIDEL",
    "4167: FLORES SEGOVIA JOCELYN",
    "3087: FLORES ZUÑIGA JOSE JUAN",
    "4473: FONSECA CHAVEZ JOSE DE JESUS",
    "0288: FRIAS RAMIREZ EVELIA",
    "3500: GALVAN PAREDES MIGUEL",
    "0106: GALVAN HERRERA IGNACIO JAIME",
    "3172: GARCIA ACOSTA J. JESUS",
    "4075: GARCIA AGUAS JUAN DANIEL",
    "4195: GARCIA CABELLO EMYLI ANYSHA",
    "2442: GARCIA CELESTINO MA. DEL ROSARIO",
    "3807: GARCIA GARCIA FIDEL",
    "0387: GARCIA HERNANDEZ JOEL",
    "3018: GARCIA HERNANDEZ JESUS ADRIAN",
    "4035: GARCIA MALDONADO VIOLETA",
    "4435: GARCIA MARTINEZ MOISES ISRAEL",
    "3358: GARCIA MARTINEZ SERAFIN",
    "1264: GARCIA MARTINEZ LUIS ALBERTO",
    "0101: GARCIA MORALES MARIA PUEBLITO",
    "4398: GARCIA MORALES EDUARDO ANTONIO",
    "4182: GARCIA PELCASTRE TANIA",
    "4368: GARCIA RODRIGUEZ GUALBERTO",
    "2656: GARIBALDI VAZQUEZ JAVIER",
    "4419: GAXIOLA GONZALEZ IVONNE",
    "0178: GAZCA GUTIERREZ ANUAR",
    "3835: GOMEZ BARBOSA MIGUEL ANGEL",
    "3336: GONZAGA VIDAL DORA CRISTINA",
    "3152: GONZAGA ARTEAGA MANUEL",
    "1661: GONZALEZ ESCUTIA ROGELIO",
    "2927: GONZALEZ FLORES DANIEL",
    "0092: GONZALEZ GUERRERO JOSE LUIS",
    "4395: GONZALEZ JAUREGUI ESQUEDA JULIETA",
    "4389: GONZALEZ LOPEZ JOSE ALBERTO",
    "2583: GONZALEZ OLGUIN MARIA BEATRIZ",
    "3682: GONZALEZ PEREZ ALBERTO",
    "0048: GONZALEZ PEREZ OSCAR",
    "0406: GONZALEZ RAMIREZ MANUEL",
    "2742: GONZALEZ SALINAS MARISOL",
    "0015: GONZALEZ BALDERAS JUAN",
    "0600: GRANADOS UGALDE J. PUEBLITO",
    "4348: GUERRERO ALEGRIA SALVADOR",
    "2144: GUERRERO LUNA JOSE JUAN",
    "3996: GUERRERO MEDINA MIGUEL",
    "3754: GUERRERO RECENDIS BALTAZAR",
    "4350: GUERRERO RESENDIZ JUDITH DE LOS ANGELES",
    "0094: GUERRERO LOPEZ JOSE ALFREDO",
    "3649: GUERRERO MARTINEZ ERIK GUILLERMO",
    "4463: GUSMAN AGUILAR JOSE GUADALUPE",
    "4484: GUTIERREZ SOTO HECTOR ULISES",
    "4460: GUZMAN JUAREZ VIVIANA ITZARELY",
    "0344: GUZMAN PEREZ JUAN MANUEL",
    "3478: HERNANDEZ BALTAZAR RODOLFO TOMAS",
    "3513: HERNANDEZ BORJA JOSE MARTIN",
    "4427: HERNANDEZ BUSTOS AGLAHE MONSERRAT",
    "3268: HERNANDEZ CASTRO FERNANDO",
    "3422: HERNANDEZ CASTRO LUIS FRANCISCO",
    "4434: HERNANDEZ CHAVEZ JAIME",
    "0351: HERNANDEZ CUELLAR JOSE",
    "0702: HERNANDEZ DIONISIO MARIA ELENA",
    "0378: HERNANDEZ ENRIQUEZ GUILLERMO",
    "2413: HERNANDEZ ESPINOSA LUIS ALFREDO",
    "4230: HERNANDEZ GALVAN GRACIELA",
    "3274: HERNANDEZ GUDIÑO SAYRA JANETHE",
    "3511: HERNANDEZ HERNANDEZ LUIS GABRIEL",
    "3196: HERNANDEZ HERNANDEZ CARLOS DANIEL",
    "3283: HERNANDEZ HERNANDEZ JAQUELINE",
    "3539: HERNANDEZ JAVIER MARTHA GABRIELA",
    "0361: HERNANDEZ LOPEZ JOSE ANGEL",
    "3654: HERNANDEZ HERNANDEZ ERIC",
    "4029: HERNANDEZ HERNANDEZ SAUL",
    "3396: HERNANDEZ LUJAN LEONARDO",
    "3568: HERNANDEZ MARTINEZ ANIBAL PASTOR",
    "0045: HERNANDEZ MONTES DIANA ANGELICA",
    "2464: HERNANDEZ MORALES LILIANA",
    "2720: HERNANDEZ MORALES JOSE CRUZ",
    "3883: HERNANDEZ MUÑOZ REBECA",
    "0075: HERNANDEZ PERCASTRE JULIO CESAR",
    "4345: HERNANDEZ RAMIREZ ADOLFO ANGEL",
    "0136: HERNANDEZ RESENDIZ MARCELINO",
    "4215: HERNANDEZ RODRIGUEZ FRANCISCO GUILLERMO",
    "2417: HERNANDEZ SALINAS JOSE LUIS",
    "4308: HERNANDEZ TERAN CRISTIAN",
    "4331: HERNANDEZ TORIZ NORA MARLET",
    "4479: HERNANDEZ TRIANO JUAN DANIEL",
    "2872: HERRERA VAZQUEZ FABIAN",
    "2845: HINOJOSA HERNANDEZ MARIA LIZBETH",
    "0229: HURTADO HERRERA JUAN MANUEL",
    "0136: ISLAS DIAZ JUAN CARLOS",
    "4408: JIMENEZ ORDOÑEZ BLANCA ESTELA",
    "4193: JIMENEZ GRANADOS ARIADNA JUKARI",
    "4391: JIMENEZ SALAZAR BRENDA",
    "0122: JIMENEZ ZAMORA ROGELIO",
    "3934: JORGE ALBA ISAAC",
    "2338: JUAREZ SUAREZ MARIA ANTONIA",
    "3176: JUAREZ SUAREZ MARIA GABRIELA",
    "2402: LARA ALVAREZ FEDERICO",
    "3952: LARRIETA PEREZ HECTOR MIGUEL",
    "0116: LEDEZMA MUÑOZ JUAN",
    "4323: LEON ORTIZ IAN VICTOR",
    "3366: LEON REYES FLORIAN ABIGAIL",
    "4477: LEON URIBE MARIO CESAR",
    "0089: LOPEZ AURELIA",
    "4468: LOPEZ BUTRON ERICK RAFAEL",
    "4322: LOPEZ CASTAÑEDA ADAN MAURICIO",
    "0105: LOPEZ CRUZ REYES",
    "0080: LOPEZ CRUZ ELEUTERIO",
    "4160: LOPEZ GALVAN MARIA YOANA",
    "4305: LOPEZ GARCIA MELISSA",
    "3246: LOPEZ GARCIA SULEIMA",
    "2683: LOPEZ LOPEZ MARICRUZ",
    "0086: LOPEZ MARTINEZ JOSE ASCENCION",
    "0035: LOPEZ MARTINEZ JOSE RAMIRO",
    "3387: LOPEZ MATA JOSE",
    "0065: LOPEZ MATA ARTURO",
    "2863: LOPEZ MORENO JOSE ANTONIO",
    "3863: LOPEZ MUÑOZ JOSE ENRIQUE",
    "4440: LOPEZ ORTIZ JOSE ALFONSO JONATAN",
    "2591: LOPEZ PEREZ JUAN",
    "4200: LOPEZ PEREZ AURELIO",
    "3407: LOPEZ RAMIREZ DIEGO ARMANDO",
    "3956: LOPEZ RAMIREZ ABRAHAM",
    "0637: LOPEZ RAMIREZ MA. DEL CARMEN",
    "3580: LOPEZ RIOS MARIO",
    "4474: LOPEZ SORIA JOSE ALBERTO",
    "3089: LOPEZ TORIBIO JESUS",
    "3872: LOYOLA PATIÑO ERIK",
    "3200: LUCAS OLGUIN JOSE",
    "0058: LUNA MARTINEZ JUAN MANUEL",
    "0052: LUNA MARTINEZ RAUL",
    "1167: LUNA AGUILAR JOSE ANTONIO",
    "3486: LUNA JIMENEZ LUIS GERARDO",
    "4410: MACEDO UGARTE JOCELIN OLIVIT",
    "4438: MACHUCA MUNGUIA EVA MARIA",
    "4356: MADERA JIMENEZ JOSE MANUEL",
    "4149: MALAGON SANCHEZ ALEJANDRA",
    "4224: MALDONADO ALVAREZ CARLOS MIGUEL",
    "2748: MANDUJANO PAREDES ANGEL",
    "4467: MARIN LUNA BRENDA KARINA",
    "1422: MARTINEZ BOCANEGRA JULIO ALBERTO",
    "4424: MARTINEZ CABRERA ARTURO",
    "4366: MARTINEZ CORREA RAMON",
    "1984: MARTINEZ OLVERA JUAN CARLOS",
    "0720: MARTINEZ PERALTA JUAN PABLO",
    "0719: MARTINEZ PERALTA HECTOR RENE",
    "4367: MARTINEZ PIÑA ANGEL",
    "1970: MARTINEZ SANCHEZ JUANA",
    "3732: MARTINEZ BALDERAS JORGE ANTONIO",
    "1258: MARTINEZ VEGA MARCO ANTONIO",
    "3705: MARTINEZ VEGA JESUS IVAN",
    "3499: MARTINEZ ALVAREZ JOSE JUAN",
    "4056: MARTINEZ ALVAREZ JUAN",
    "3083: MARTINEZ AVILA LUIS FELIPE",
    "4333: MAYA RIVERA BLANCA ERIKA",
    "3454: MEDINA VAZQUEZ JAVIER",
    "3405: MEDINA MARTINEZ JOSE GUADALUPE",
    "4480: MEDINA MENTADO JUAN ALBERTO",
    "2480: MEJIA MEJIA JONATHAN",
    "3398: MEJIA PATIÑO MARIA GUADALUPE",
    "3328: MENA AGUILAR JULIO CESAR",
    "4383: MENA AGUILAR CRISTIAN GUSTAVO",
    "2979: MENDEZ CALIXTO YURI YADIRA",
    "0293: MENDEZ GALVEZ GLADIS NANCY",
    "4447: MENDEZ SANTIAGO JESUS DANIEL",
    "3267: MENDOZA SANCHEZ ADRIAN",
    "4217: MOLINA JIMENEZ MIGUEL ANGEL",
    "0369: MOLINA VAZQUEZ JOSE FERNANDO",
    "2607: MOLINA AGUILAR JULIO ALFREDO",
    "3779: MOLINA MATIAS NELY",
    "4459: MONICO CABRERA LUIS ANGEL",
    "3727: MONTES MALAGON JESUS ALEJANDRO",
    "0085: MONTES MORALES J ROSARIO",
    "3239: MONTES HERNANDEZ ISMAEL",
    "3535: MORAN ESTRADA LEONARDO",
    "4311: MORENO ALVARADO JUAN MANUEL",
    "1048: MORALES SANCHEZ JAIRO DANIEL",
    "4028: MORALES CERVANTES MARIA DEL CARMEN",
    "3579: MUÑOZ PEREZ PABLO",
    "3973: MUÑOZ LEON JESUS MANUEL",
    "4254: MUZQUIZ CARRANZA OSWALDO",
    "2206: NAVARRO ESCALANTE ALEJANDRO",
    "0031: NERI GARDUNO ISRAEL",
    "2535: NUÑEZ GUDIÑO MA. SILVIA",
    "3808: OLVERA MARTINEZ JUAN",
    "3235: OLVERA TORRES CRISTINA",
    "3002: OLVERA CORONEL MARTHA PATRICIA",
    "4301: OLVERA TREJO OSCAR DAVID",
    "3543: ORTEGA TALAVERA IVETTE ALEXA",
    "1832: ORTIZ LOPEZ LIGORIO",
    "2726: ORTIZ LOPEZ MAURICIO",
    "2406: ORTIZ RUIZ SUSANA",
    "1867: OTERO GONZALEZ ALEJANDRO",
    "0322: PACHECO HERRERA DANIEL ALEJANDRO",
    "4341: PACHECO HERNANDEZ GREGORIO",
    "3764: PALACIOS GONZALEZ MARCOS EDUARDO",
    "0701: PALACIOS BARCO MARIA TRINIDAD MICAELA",
    "2750: PANIAGUA HERNANDEZ MARIA LUISA",
    "4412: PAREDES RESENDIZ MIGUEL ANGEL DIEGO",
    "3540: PARRAL AVELINO MARTIN",
    "4329: PEÑA GARCIA SOFIA",
    "2901: PEÑA PETRONILO SERGIO",
    "4318: PEÑA SANTOS CARLA IVONNE",
    "2255: PEREZ BASALDUA JUAN CARLOS",
    "1098: PEREZ CARREON ALBERTO BALTASAR",
    "3967: PEREZ HERNANDEZ LOURDES",
    "3477: PEREZ MENDO JESUS EDUARDO",
    "2914: PEREZ MARTINEZ JUAN JOSE",
    "4194: PEREZ MORALES JUAN DANIEL",
    "4462: PEREZ PEREZ ANGELICA",
    "3516: PEREZ RODRIGUEZ RODRIGO",
    "3666: PEREZ RUIZ JOSE MANUEL",
    "0025: PEREZ LOPEZ GABRIEL",
    "0041: PEREZ LOPEZ PABLO",
    "0298: PEREZ CORDOVA MIRNA DIANA",
    "4432: PESQUERA RODRIGUEZ PAULINA",
    "3877: PILAR ESCOBEDO JUANA FERNANDA",
    "0038: PINA TREJO JOSE ALFREDO",
    "3884: PIÑA MENDIETA VICTOR MANUEL",
    "0340: PRIETO MICHEL EDUARDO MARTIN",
    "4232: QUINTANAR ORIA GUILLERMO",
    "4264: RAMIREZ ARAUJO CARLOS",
    "3916: RAMIREZ ARREOLA TERESA",
    "2943: RAMIREZ CASTAÑEDA LUIS RODOLFO",
    "3148: RAMIREZ DE JESUS KARLA",
    "3995: RAMIREZ GARCIA ESTEBAN",
    "2758: RAMIREZ HERNANDEZ PATRICIA",
    "3529: RAMIREZ HERNANDEZ CESAR",
    "3232: RAMIREZ LOPEZ LAURA ANGELICA",
    "4111: RAMIREZ GUTIERREZ FRANCISCO",
    "2373: RAMIREZ MARTINEZ JORGE",
    "0986: RAMIREZ MARTINEZ LUCERO",
    "1707: RAMIREZ PACHECO NICOLAS",
    "4270: RAMIREZ PEREZ BERNARDO",
    "3953: RAMIREZ RAMIREZ MAURICIO",
    "4062: RAMIREZ RESENDIZ JOSE DEL CARMEN",
    "4024: RAMIREZ RUBIO LUIS OSCAR",
    "2096: RAMIREZ SORIA CARLOS GIOVANNY",
    "4307: RAMIREZ ZUÑIGA JONATHAN MAEL",
    "0917: RAMIREZ FELIX ISAURA",
    "3419: RUBIO CHAVEZ EDUARDO",
    "0175: RANGEL MEDINA JOSE ANDRES",
    "0164: RANGEL MEDINA JOSE ARMANDO",
    "3523: RAMOS LORENZANA FERNANDO",
    "2534: RAMOS HERNANDEZ JAZMIN ABIGAIL",
    "0291: RAMOS PICHARDO MARIA LAURA",
    "4354: RENDON MONTES MARCOS",
    "0603: RESENDIZ HIPOLITO MARCELINO",
    "4032: RESENDIZ ORDUÑA VICENTE FRANCISCO",
    "3056: RICO ESCOBEDO JUAN GABRIEL",
    "4466: RIVERA VACA TANIA SOFIA",
    "1328: RIVERA HERNANDEZ MARIO",
    "0307: RIVERA GONZALEZ JUAN ANTONIO",
    "3630: ROBLES TAPIA LUIS ANGEL",
    "4278: RODRIGUEZ LOPEZ JUAN JAVIER",
    "0209: RODRIGUEZ SOTO ALFREDO SIGFRIDO",
    "4454: RODRIGUEZ TORRES ANA ISABEL",
    "3314: RODRIGUEZ VALDELAMAR MARIA LAURA",
    "3241: RODRIGUEZ HERNANDEZ GUADALUPE",
    "4483: ROJAS LOZANO JOSE MARTIN",
    "4349: ROJAS MORALES DIANA KAREN YUMA",
    "4339: ROJAS PONCE MARIA TERESA",
    "0447: ROJAS FERRETIZ ADRIANA",
    "4089: ROSALES NICOLAS NOE",
    "3815: ROSALES ROMERO ABRAHAM",
    "3035: ROSALES MARTINEZ MARIA GUADALUPE",
    "4315: ROSAS LOPEZ TANIA",
    "4409: ROSAS CRUZ VIVIANA",
    "4444: RUIZ BACILIO HECTOR",
    "4086: RUIZ GUTIERREZ DANIEL RICARDO",
    "4388: RUIZ GUERRERO ZULEMA GUADALUPE",
    "0173: RUIZ PEREZ VALENTIN",
    "3901: SABIDO QUINTERO ILSSE MARIANA",
    "4328: SALAZAR LOPEZ ELVIRA",
    "3782: SALINAS ARIAS JOSE LUIS",
    "4344: SALINAS DOMINGUEZ BRANDON BRYAN",
    "4458: SALINAS LOPEZ ALEJANDRO",
    "2336: SALINAS SERVIN JORGE ALBERTO",
    "4310: SALVADOR CONTRERAS ARCADIO",
    "1171: SAMANIEGO CALZONTZI SABAS",
    "1062: SANCHEZ ARELLANO MARCELO",
    "1063: SANCHEZ ARELLANO AARON",
    "3242: SANCHEZ CRUZ FRANCISCO",
    "4334: SANCHEZ GONZALEZ OSCAR ANDRES",
    "4220: SANCHEZ GONZALEZ OSWALDO JESUS",
    "0294: SANCHEZ HERNANDEZ ANA PATRICIA",
    "3888: SANCHEZ LUNA JESUS ALEJANDRO",
    "2940: SANCHEZ MANDUJANO MIGUEL",
    "4092: SANCHEZ RODRIGUEZ DIANA CECILIA",
    "1121: SANCHEZ ROMERO ROBERTO",
    "4239: SANCHEZ ZAGALA ERIK",
    "4457: SANCHEZ ZAGALA JESUS",
    "2087: SANDIA MARTINEZ ROBERTO",
    "0624: SANTES OLARTE JAVIER",
    "2147: SOBERANES MORENO SARA",
    "3452: SOLANO ORTIZ FLOR DE MARIA",
    "3364: SORIA ORTIZ CESAR",
    "2551: SORIA ORTIZ CARLOS IVAN",
    "4219: SUAREZ RAMIREZ CITLALI REGINA",
    "4225: SUAREZ OLVERA MARIA GUADALUPE",
    "1028: TAPIA SERRATO FRANCISCO",
    "3560: TAVAREZ PEREZ ALEJANDRA",
    "4243: TEPOLE LECHUGA SILVIANO",
    "3959: TERRAZAS TAPIA LUIS ANGEL",
    "4478: TIMOTEO MOYA JOSE LUIS",
    "0142: TORRES URIBE JOSE MARGARITO",
    "3785: TORRES MORENO JOSE MARTIN",
    "2363: TREJO HERNANDEZ ARMANDO",
    "2409: TREJO CHAVEZ JOSE SERGIO",
    "0650: TREJO CHAVEZ JOSE GUADALUPE",
    "3164: TRUEBA GASCA JOSE OSWALDO",
    "4169: VALDEZ PACHECO JUAN LUIS",
    "4234: VALLEJO MAURICIO M DEL CARMEN",
    "1907: VARGAS DE JESUS FRANCISCO",
    "3817: VASQUEZ QUINTANA MARIA ARASELI",
    "4428: VASQUEZ ESPINDOLA JONATHAN ALAIN",
    "3571: VAZQUEZ NAVARRETE ALFONSO",
    "3409: VAZQUEZ GUTIERREZ DULCE MARIA",
    "4271: VEGA PEREZ ALEJANDRO",
    "4138: VEGA VEGA EMMANUEL",
    "1659: VEGA MANDUJANO JAIME",
    "0150: VEGA GONZALEZ ERNESTO",
    "3853: VEGA ALVA JUAN CARLOS",
    "3736: VELASCO SOTO JAME SAMANTHA",
    "4189: VELAZQUEZ LOZANO DANIEL",
    "4351: VILLEGAS PONCE CARLOS SANTIAGO",
    "1747: ZAMANIEGO CALZONCIT JOSE JESUS",
    "1168: ZAMANIEGO CALZONZI ANDRES",
    "3066: ZAMORA LEDEZMA DALILA",
    "4361: ZAMUDIO MORALES EMMANUEL",
    "4443: ZUÑIGA CHAVEZ DAVID SANTIAGO",
    "2056: ZUÑIGA DE SANTIAGO DANIEL ALEXANDER",
    "1329: ZUÑIGA RIVERA SALVADOR",
    "1269: ZUÑIGA RIVERA MA. GUADALUPE",
    "0016: ZUÑIGA TREJO SALVADOR"
];

const UNITS = [
      "MY-2601", "QI-091","QI-138", "QI-139", "QI-144", "QI-158", "QI-159", "QI-163", "QI-170", "QI-178", "QI-179", "QI-193", "QI-201", "QI-202", "QI-270", "QI-271", "QI-330", "QI-331", "QI-332", "QI-370", "QI-415", "QI-428", "QI-433", "QI-768", "QI-769", "QI-770", "QI-772", "QI-773", "QI-774", "QI-777", "QI-799", "QI-1006", "QI-1012", "QI-1035", "QI-1070", "QI-1113", "QI-1154", "QI-1175", "QI-1233", "QI-1234", "QI-1235", "QI-1236", "QI-1237", "QI-1238", "QI-1239", "QI-1240", "QI-1241", "QI-1242", "QI-1243", "QI-1244", "QI-1245", "QI-1246", "QI-1247", "QI-1248", "QI-1249", "QI-1250", "QI-1251", "QI-1252", "QI-1258", "QI-1259", "QI-1396", "QI-1397", "QI-1439", "QI-1697", "QI-1698", "QI-1699", "QI-1700", "QI-1701", "QI-1703", "QI-1715", "QI-1716", "QI-1748", "QI-1749", "QI-1750", "QI-1752", "QI-1823", "QI-1900", "QI-1908", "QI-1909", "QI-1910", "QI-1921", "QI-1922", "QI-1923", "QI-1924", "QI-1927", "QI-1932", "QI-1933", "QI-1934", "QI-1935", "QI-1936", "QI-1937", "QI-1938", "QI-1940", "QI-1942", "QI-1943", "QI-1944", "QI-1947", "QI-1948", "QI-1949", "QI-1950", "QI-2029", "QI-2076", "QI-2077", "QI-2078", "QI-2079", "QI-2129", "QI-2130", "QI-2131", "QI-2134", "QI-2146", "QI-2147", "QI-2148", "QI-2149", "QI-2150", "QI-2151", "QI-2182", "QI-2329", "QI-2330", "QI-2336", "QI-2337", "QI-2338", "QI-2357", "QI-2418", "QI-2419","QI-2455", "QI-2456", "QI-2536", "QI-2648", "QI-2662", "QI-2716", "QI-2717", "QI-2718", "QI-2733", "QI-2753", "QI-2754", "QI-2755", "QI-2879", "QI-2880", "QI-2881", "QI-2907", "QI-2960", "QI-2961", "QI-3052", "QI-3053", "QI-3054", "QI-3055","QI-3092","QI-3093","QI-3094","QI-3095","QI-3096","QI-3097","QI-3098","QI-3099","QI-3100", "SM-2611"
];

const TALLERES = [
    "Taller Central",
    "Taller Norte", 
    "Taller Sur",
    "Taller Externo",
    "Proveedor Autorizado"
];

// TIPOS DE RUTA (NUEVO)
const TIPOS_RUTA = [
    "Utilitario",
    "Mantenimiento",
    "Montacargas",
    "Cilindros",
    "Autotanque"
];

// RUTAS ORGANIZADAS POR TIPO
const RUTAS_POR_TIPO = {
    "Utilitario": [
        "Utilitario"
    ],
    "Mantenimiento": [
        "Mantenimiento"
    ],
    "Montacargas": [
        "Montacargas"
    ],
    "Cilindros": [
        "C-001", "C-002", "C-003", "C-004", "C-005", "C-006", "C-007", "C-008", "C-009", "C-010",
        "C-011", "C-012", "C-013", "C-014", "C-015", "C-016", "C-017", "C-018", "C-019", "C-020",
        "C-021", "C-022", "C-023", "C-024", "C-025", "C-026", "C-027", "C-028", "C-029", "C-030",
        "C-031", "C-032", "C-033", "C-034", "C-035", "C-036", "C-037", "C-038", "C-039", "C-040",
        "C-041", "C-042", "C-043", "C-044", "C-045", "C-046", "C-047", "C-048", "C-049", "C-050",
        "C-051", "C-052", "C-053", "C-054 VESPERTINO", "C-055", "C-056 VESPERTINO", "C-057", "C-058", 
        "C-059", "C-060", "C-061", "C-062", "C-063", "C-064", "C-065", "C-066 VESPERTINO", "C-067", 
        "C-068", "C-069", "C-070", "C-071", "C-072", "C-073", "C-074", "C-075", "C-076", "C-077", 
        "C-078", "C-079", "C-080", "C-081", "C-082 VESPERTINO", "C-083", "C-084", "C-085", "C-086"
    ],
    "Autotanque": [
        "M-002", "M-004", "M-005", "M-006", "M-008", "M-009", "M-010", "M-011", "M-013", "M-020",
        "M-022", "M-028", "M-029", "M-030", "M-031", "M-033", "M-034", "M-037", "M-041", "M-042",
        "M-046", "M-049", "M-052", "M-053", "M-055", "M-058", "M-059", "M-060", "M-071", "M-072",
        "M-074", "M-076", "M-077", "M-078", "M-015 VESPERTINO", "M-018 VESPERTINO", "M-019 VESPERTINO",
        "M-025 VESPERTINO", "M-036 VESPERTINO", "M-038 VESPERTINO", "M-039 VESPERTINO", "M-043 VESPERTINO",
        "M-044 VESPERTINO", "M-045 VESPERTINO", "M-047 VESPERTINO", "M-048 VESPERTINO", "M-057 VESPERTINO",
        "M-066 VESPERTINO"
    ]

    
};

// PUNTOS DE INSPECCIÓN PARA TIPOS NORMALES (Utilitario, Mantenimiento, Montacargas, Cilindros)
const INSPECTION_POINTS_NORMAL = [
    { id: "head_interior", label: "INTERIOR DE LA UNIDAD", isHeader: true },
    { id: "int_indicadores", label: "Indicadores del tablero (Funcionan)", critical: true },
    { id: "int_calentador", label: "Calentador-Desempañador (Funciona)", critical: true },
    { id: "int_herramientas", label: "Caja de herramientas y martillo (A bordo)", critical: true },
    { id: "int_lampara", label: "Lámpara de mano (A bordo)", critical: true },
    { id: "int_cinturon", label: "Cinturón de seguridad (Buen estado y funciona)", critical: true },
    { id: "int_parabrisas", label: "Parabrisas (Sin daño)", critical: true },
    { id: "int_limpiadores", label: "Limpiadores (Funcionando)", critical: true },
    { id: "int_espejos", label: "Espejos retrovisores (Sin daño)", critical: true },
    { id: "int_frenos", label: "Sistema de frenos (Funciona)", critical: true },

    { id: "head_frente", label: "FRENTE EXTERIOR", isHeader: true },
    { id: "frente_defensa", label: "Defensa (Sujeción correcta, en buen estado)", critical: true },
    { id: "frente_luces", label: "Sistema de luces (Funcionando)", critical: true },

    { id: "head_laterales", label: "LADO IZQUIERDO Y DERECHO", isHeader: true },
    { id: "lat_tapon", label: "Tapón tanque de combustible (Cierre hermético)", critical: true },
    { id: "lat_luces", label: "Sistema de luces (Funcionando)", critical: true },
    { id: "lat_refaccion", label: "Llanta de refacción (Presión correcta y sin daños)", critical: true },
    { id: "lat_llantas", label: "Llantas (Presión de fabricante y sin daños)", critical: true },
    { id: "lat_rines", label: "Rines (Sin daños)", critical: true },
    { id: "lat_birlos", label: "Birlos y tuercas (Completos y sin daños)", critical: true },
    { id: "lat_loderas", label: "Guardafangos / Loderas (Completos y sin daños)", critical: true },

    { id: "head_posterior", label: "PARTE POSTERIOR E INFERIOR", isHeader: true },
    { id: "post_luces", label: "Sistema de luces (Funcionando)", critical: true },
    { id: "post_reflejantes", label: "Reflejantes visibles (En buen estado)", critical: true },
    { id: "post_defensa", label: "Defensa (Sujeción correcta, sin daños)", critical: true },
    { id: "post_escape", label: "Escape (Sujeto y sin daño)", critical: true },
    { id: "inf_muelles", label: "Muelles (Completos)", critical: true },

    { id: "head_emergencia", label: "EQUIPO DE EMERGENCIA Y ESTRUCTURA", isHeader: true },
    { id: "em_botiquin", label: "Botiquín de primeros auxilios (A bordo)", critical: true },
    { id: "em_extintor", label: "Extintor 9kg tipo ABC (Sujeto, fecha vigente)", critical: true },
    { id: "em_senales", label: "Señales reflejantes y Calzas (A bordo, sin daño)", critical: true },
    { id: "est_plataforma", label: "Plataforma y armazón perimetral (Uniforme y completa)", critical: true },
    { id: "est_sujecion", label: "Sistema de aseguramiento y enganche (Sin daño)", critical: true },
    { id: "est_recipientes", label: "Recipientes (En posición vertical y asegurados)", critical: true },
    
    { id: "head_letreros", label: "LETREROS, SEÑALES Y AVISOS", isHeader: true },
    { id: "letreros", label: "Letreros y avisos (Claros, legibles y no obstruidos)", critical: true }
];

// PUNTOS DE INSPECCIÓN PARA AUTOTANQUE (DIFERENTE)
const INSPECTION_POINTS_AUTOTANQUE = [
    // RECIPIENTE, VÁLVULAS, ACCESORIOS Y SISTEMA DE TRASIEGO
    { id: "head_recipiente", label: "RECIPIENTE, VÁLVULAS, ACCESORIOS Y SISTEMA DE TRASIEGO", isHeader: true },
    { id: "at_recipiente", label: "Recipiente No Desmontable (Libre de abolladuras, protuberancias, etc.)", critical: true },
    { id: "at_coples", label: "Coples (Sin fuga)", critical: true },
    { id: "at_valvulas_acc", label: "Válvulas y accesorios (Sin fuga)", critical: true },
    { id: "at_valvula_interna", label: "Válvula interna (Abre/cierra correctamente)", critical: true },
    { id: "at_indicadores_fuga", label: "Indicador de presión, temp. y nivel (Sin fuga y funciona)", critical: true },
    { id: "at_indicadores_nivel", label: "Nivel de llenado del Recipiente (No excede el 90%)", critical: true },
    { id: "at_bomba", label: "Bomba de trasiego (Tornillería completa y anclaje correcto)", critical: true },
    { id: "at_medicion", label: "Sistema de medición (Sin fuga, tornillería completa, sin corrosión)", critical: true },
    { id: "at_manguera_estado", label: "Manguera (Sin protuberancias, cortes, raspaduras)", critical: true },
    { id: "at_manguera_recubrimiento", label: "Manguera (Recubrimiento de hule y malla interna sin daño)", critical: true },
    { id: "at_manguera_accesorios", label: "Manguera (Tornillería completa, sin desgaste en accesorios)", critical: true },
    { id: "at_junta_rotatoria", label: "Junta rotatoria (Sin fuga, sin cables expuestos y funcionando)", critical: true },
    { id: "at_valvula_suministro", label: "Válvula de suministro (Sin daños y sin fugas)", critical: true },

    // INTERIOR (CABINA)
    { id: "head_interior_at", label: "INTERIOR (CABINA)", isHeader: true },
    { id: "at_documentos", label: "Documentos (Permiso, T. Circulación, Reglamento, PRE, HDS a bordo)", critical: true },
    { id: "at_herramientas", label: "Caja de herramientas y martillo (A bordo)", critical: true },
    { id: "at_lampara", label: "Lámpara de mano (A bordo)", critical: true },
    { id: "at_indicadores", label: "Indicadores del tablero (Funcionan)", critical: true },
    { id: "at_calentador", label: "Calentador-Desempañador (Funciona)", critical: true },
    { id: "at_cinturon", label: "Cinturón de seguridad (En buen estado y funciona)", critical: true },
    { id: "at_parabrisas", label: "Parabrisas (Sin daño)", critical: true },
    { id: "at_limpiadores", label: "Limpiadores (Funcionan)", critical: true },
    { id: "at_espejos", label: "Espejos retrovisores (Sin daño)", critical: true },
    { id: "at_frenos", label: "Sistema de frenos (Funciona)", critical: true },

    // FRENTE EXTERIOR
    { id: "head_frente_at", label: "FRENTE EXTERIOR", isHeader: true },
    { id: "at_frente_defensa", label: "Defensa (Sujeción correcta, sin daños)", critical: true },
    { id: "at_frente_luces", label: "Sistema de luces (Funcionan)", critical: true },
    { id: "at_frente_escape", label: "Escape (Sujeto y sin daño)", critical: true },

    // LADO IZQUIERDO Y LADO DERECHO
    { id: "head_laterales_at", label: "LADO IZQUIERDO Y LADO DERECHO", isHeader: true },
    { id: "at_lat_tapon", label: "Tapón del tanque de combustible (Cierre hermético)", critical: true },
    { id: "at_lat_luces", label: "Sistema de luces (Funcionan)", critical: true },
    { id: "at_lat_refaccion", label: "Llanta de refacción (Presión correcta y sin daños)", critical: true },
    { id: "at_lat_llantas", label: "Llantas (Presión correcta y sin daños)", critical: true },
    { id: "at_lat_rines", label: "Rines (Sin daños)", critical: true },
    { id: "at_lat_birlos", label: "Birlos y tuercas (Completos y sin daños)", critical: true },
    { id: "at_lat_loderas", label: "Guardafangos / Loderas (Completos y sin daños)", critical: true },
    { id: "at_lat_escalera", label: "Escalera (Bien sujeta)", critical: true },

    // PARTE POSTERIOR DE LA UNIDAD
    { id: "head_post_at", label: "PARTE POSTERIOR DE LA UNIDAD", isHeader: true },
    { id: "at_post_luces", label: "Sistema de luces (Funcionando)", critical: true },
    { id: "at_post_defensa", label: "Defensa (Que exista, sujeción correcta y sin daños)", critical: true },

    // PARTE INFERIOR
    { id: "head_inf_at", label: "PARTE INFERIOR DE LA UNIDAD", isHeader: true },
    { id: "at_inf_cinta", label: "Cinta estática (Que toque el piso)", critical: true },

    // EQUIPO DE EMERGENCIA
    { id: "head_em_at", label: "EQUIPO DE EMERGENCIA", isHeader: true },
    { id: "at_em_botiquin", label: "Botiquín y Extintor 9kg ABC (A bordo, vigente)", critical: true },
    { id: "at_em_senales", label: "Señales, Letreros y Calzas (A bordo)", critical: true },

    // LETREROS, SEÑALES Y AVISOS
    { id: "head_letreros_at", label: "LETREROS, SEÑALES Y AVISOS", isHeader: true },
    { id: "at_letreros", label: "Letreros, señales y avisos (Claros, legibles y no obstruidos)", critical: true }
];


// Tipos de mantenimiento
const TIPOS_MANTENIMIENTO = [
    "Mantenimiento Correctivo",
    "Mantenimiento Preventivo", 
    "Otras Reparaciones"
];

// Puntos críticos de revisión
const PUNTOS_CRITICOS = [
    "Luces en general",
    "Cinta estática y banderolas",
    "Sellos manguera carburación ambas puntas",
    "Niveles (Agua, aceite, transmisión)",
    "Perifoneo",
    "Espejos",
    "Presión de aire llantas",
    "Muelles"
];

// Configuración de imagen 
const LOGO_URL = "img/logo.png";

// Configuración de Supabase
const SUPABASE_CONFIG = {
    URL: "https://rwnowbeapticgkhldkoi.supabase.co",
    KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3bm93YmVhcHRpY2draGxka29pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1MTAzNTYsImV4cCI6MjA5MTA4NjM1Nn0.JXeRHyb3LMhMWdjCme6wLdZGunixTyJxX0YE_4L2644"
};

// Función para obtener los puntos de inspección según el tipo de ruta
function getInspectionPointsByRouteType(routeType) {
    if (routeType === "Autotanque") {
        return INSPECTION_POINTS_AUTOTANQUE;
    } else {
        // Para Utilitario, Mantenimiento, Montacargas, Cilindros y cualquier otro
        return INSPECTION_POINTS_NORMAL;
    }
}

// Función para obtener las rutas según el tipo
function getRoutesByType(routeType) {
    return RUTAS_POR_TIPO[routeType] || [];
}

// Exportar datos para uso global
if (typeof window !== 'undefined') {
    window.CONFIG = {
        OPERATORS,
        UNITS,
        TALLERES,
        TIPOS_RUTA,
        RUTAS_POR_TIPO,
        TIPOS_MANTENIMIENTO,
        PUNTOS_CRITICOS,
        INSPECTION_POINTS_NORMAL,
        INSPECTION_POINTS_AUTOTANQUE,
        getInspectionPointsByRouteType,
        getRoutesByType,
        LOGO_URL,
        SUPABASE: SUPABASE_CONFIG
    };
}